module.exports = {
  sidebars:{
    'Getting Started': [
      'Overview/Welcome',
      'Overview/Dynamics365',
      'Overview/ViewsCharts',
      'Overview/Dashboards',
    //  'Overview/SecurityRoles'
     ],
    'Setup': [
      'AdminSetup/BusinessUnit',
    'AdminSetup/SecurityRoles',
    'AdminSetup/Account', 
    'AdminSetup/HealthcareService',
    'AdminSetup/InsurancePlan',
   'AdminSetup/FeeSchedules',
    'AdminSetup/Location',
    'AdminSetup/EVVSetup',
    'AdminSetup/QualificationDefinition',
    'AdminSetup/GoalBankLibrary',
  ],
  // 'Clinical Setup':[
  //   'ClinicalSetup/Coverage',
  //   'ClinicalSetup/Authorizations',
  //   'ClinicalSetup/CareTeamAssignment',
  //   'ClinicalSetup/Contacts',
  // ],
  'CRM':[
   'CRM/Opportunities',
   'CRM/Auth Workflows',
  ],
  'Patients':[
    'Patients/PatientOverview',
   // 'Patients/Location',
    'Patients/Connection',
    'Patients/Conditions',
    'Patients/EpisodeOfCare',
    'Patients/Coverages',
    'Patients/Authorization',
    'Patients/AuthorizationServices',
    'Patients/CareTeamParticipants',
    //'Patients/CareTeamAssignments',
    //'Patients/PatientEncounters',
    'Patients/PatientCalendar',
  ],
  'Practitioners':[
    'Practitioners/BasicInfo',
    'Practitioners/PractitionerRole',    
    'Practitioners/Qualifications',
    //'Practitioners/CareTeamAssignment',
   // 'Practitioners/PractitionerEncounters',
    'Practitioners/PractitionerCalendar',
   ],
 'Scheduling':[
  'Scheduling/SingleEncounters',
  'Scheduling/RecurringEncounters',
  'Scheduling/ScheduleAssistance',
  'Scheduling/CareTeamAssignments',
  'Scheduling/EncounterValidations',
  'Scheduling/DeactivateEncounters',
  'Scheduling/UnsubmitEncounters',
  'Scheduling/Utilization',
 ],
 'Payroll':[
  'Payroll/Contracts',
  'Payroll/PayrollItems',
 ],
 'Billing':[
  'Billing/BillingSetup',
  'Billing/ChargePeriods',
  'Billing/ClaimSettings',
  'Billing/ClaimItems',
  'Billing/Claims',
 ],
 'RCM':[
  'RCM/RCMworkflow',
  
  'RCM/Payment',
  //'RCM/Transactions',
  'RCM/Remits',
  'RCM/Cases',
  'RCM/RCMDashboards',
 ],

 'Tips & Tricks':[
  'TT/Tip1',
  'TT/Tip2',
  'TT/Tip3',
  'TT/Tip4',
  'TT/Tip5',
  'TT/Tip6',
  'TT/Tip7',
  'TT/Tip8',
  'TT/Tip9',
  'TT/Tip10',
  'TT/Tip11',
 ],

  'Release Notes':[
    'Release Notes/AC 4.0.5',
  'Release Notes/RCM 4.0.4',
  'Release Notes/AC 4.0.3',
  'Release Notes/AC 4.0.2',
  'Release Notes/RCM 4.0.1',
  'Release Notes/AC 4.0.1',
  'Release Notes/AC 4.0.0',
 ],

  },
};